// Generated by https://quicktype.io

export interface User {
    name:      string;
    lastname1: string;
    lastname2: string;
    birthday:  string;
    email:     string;
    password:  string;
}
